spring.application.name=solicitudes
server.port=8080

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Importar archivo .env opcional para desarrollo local
spring.config.import=optional:file:.env[.properties]

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/solicitudes}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Auth Service
auth.service.url=http://localhost:8081
jwt.secret=${JWT_SECRET:java_spring_boot_micro_servicio_auth_security_2026_project_solicitudes}
